app:
  build: .
  command: python -u main.py
  ports:
    - "80:5000"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:latest
  hostname: mongodb
  environment:
    - MONGO_INITDB_DATABASE=playpop
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
  
  ports:
    - 27017:27017